name = "UnitaryMagicGeneration"
uuid = "1234abcd-5678-90ef-ghij-1234567890ab"
authors = ["Dominik Szombathy <szombathy.dominik@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c51"
Random = "9a3f8981-9b91-5b628-cc02-add41d55d87f"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32611b"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f2afa"

[targets]
test = ["Test"]
